esphome:
  name: dual-role-1
  friendly_name: SesameDualRole1
  platformio_options:
    build_flags:
    - -std=gnu++17 -Wall -Wextra
    - -DMBEDTLS_DEPRECATED_REMOVED
# Configure the maximum number of connections as required (maximum: 9)
    - -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=6
    - -DCONFIG_NIMBLE_CPP_LOG_LEVEL=0
    build_unflags:
    - -std=gnu++11
external_components:
- source:
    type: git
    url: https://github.com/homy-newfs8/esphome-sesame_server
    ref: v0.1.0
  components: [ sesame_server ]
- source:
    type: git
    url: https://github.com/homy-newfs8/esphome-sesame3
    ref: v0.13.0
  components: [ sesame ]
# - source: '../esphome/esphome/components2'
#   components: [ sesame_server ]

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

## Enable logging
logger:
  level: DEBUG

sesame_server:
  # id: sesame_server_1
  address: !secret sesame_server_my_address
  uuid: !secret sesame_server_my_uuid
  triggers:
  - name: Sesame Touch 1
    id: touch_1
    address: !secret touch_1_address
    history_tag:
      id: touch_1_tag
      name: "Sesame_Touch_tag"
    on_event:
      then:
        - lambda: |-
            ESP_LOGD("example", "Event '%s'/'%s' triggered", event_type.c_str(), id(touch_1).get_history_tag().c_str());
            if (event_type == "unlock" && id(touch_1).get_history_tag() == "Master Key Card") {
              id(bot_2).run(0);
            }
  - name: Remote 1
    address: !secret remote_address
    on_event:
      then:
        - lambda: |-
            ESP_LOGD("example", "Event '%s' triggered", event_type.c_str());
            if (event_type == "lock") {
              id(bot_2).run(0);
            } else if (event_type == "unlock") {
              id(bot_2).run(1);
            }

sesame:
- id: bot2
  model: sesame_bot_2
  address: !secret bot2_address
  secret: !secret bot2_secret
  bot:
    id: bot_2
