esphome:
  name: sesame-server-1
  friendly_name: SesameServer1
  includes:
    - <libsesame3bt/util.h>
  platformio_options:
    build_flags:
      - -Wall
      - -Wextra
      - -DUSE_FRAMEWORK_MBEDTLS_CMAC
external_components:
  - source:
      type: git
      url: https://github.com/homy-newfs8/esphome-sesame_server
      ref: v0.13.3
    components: [sesame_server]
  # - source: "../esphome/esphome/components2"
  #   components: [sesame_server]

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_ENABLED: y
      CONFIG_BT_NIMBLE_ENABLED: y
      # Configure the maximum number of connections as required (maximum: 9)
      CONFIG_BT_NIMBLE_MAX_CONNECTIONS: "6"
      CONFIG_BT_NIMBLE_CRYPTO_STACK_MBEDTLS: y

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passphrase

  ## Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

## Check memory usage
# debug:
#   update_interval: 10s
# sensor:
#   - platform: debug
#     free:
#       name: "Heap Free"
#     block:
#       name: "Heap Max Block"
#     loop_time:
#       name: "Loop Time"

## Enable logging
logger:
  level: DEBUG

## Enable Home Assistant API
api:

button:
  - platform: template
    name: "Reset Sesame Server"
    on_press:
      - lambda: |-
          id(sesame_server_1).reset();

sesame_server:
  id: sesame_server_1
  uuid: !secret test_sesame_server_uuid
  triggers:
    - name: Sesame Touch 1
      id: touch_1
      address: !secret touch_1_address
      history_tag:
        name: "Sesame Touch tag"
      history_tag_type:
        name: "Sesame Touch history_tag_type"
      connection_sensor:
        name: "Sesame Touch connection"
      scaled_voltage:
        name: "Sesame Touch scaled_voltage"
      battery_pct:
        name: "Sesame Touch battery_pct"
      scaled_voltage2:
        name: "Sesame Touch scaled_voltage2"
      battery_pct2:
        name: "Sesame Touch battery_pct2"
      extra:
        name: "Sesame Touch extra"
      on_event:
        then:
          - lambda: |-
              ESP_LOGD("example", "Touch '%s'/'%s'/%.0f/%.2fV/%.1f%%/%.2fV/%.1f%% triggered", event_type.c_str(), id(touch_1)->get_history_tag().c_str(), id(touch_1)->get_history_tag_type(), id(touch_1)->get_scaled_voltage(), id(touch_1)->get_battery_pct(), id(touch_1)->get_scaled_voltage2(), id(touch_1)->get_battery_pct2());
              if (id(touch_1)->get_extra().length() > 0) {
                ESP_LOGD("example", "Touch extra: %s", libsesame3bt::core::util::bin2hex(id(touch_1)->get_extra().data(), id(touch_1)->get_extra().length()).c_str());
              } else {
                ESP_LOGD("example", "Touch extra: <empty>");
              }
    - name: Remote 1
      id: remote_1
      address: !secret remote_address
      on_event:
        then:
          - lambda: |-
              ESP_LOGD("example", "Remote '%s'/'%s'/%.0f/%.2fV/%.1f%% triggered", event_type.c_str(), id(remote_1)->get_history_tag().c_str(), id(remote_1)->get_history_tag_type(), id(remote_1)->get_scaled_voltage(), id(remote_1)->get_battery_pct());
    - name: Open Sensor 2
      id: open_sensor_2
      uuid: !secret open_sensor_2_uuid
      history_tag:
        name: "Open Sensor 2 history_tag"
      history_tag_type:
        name: "Open Sensor 2 history_tag_type"
      connection_sensor:
        name: "Open Sensor 2 connection"
      scaled_voltage:
        name: "Open Sensor 2 scaled_voltage"
      battery_pct:
        name: "Open Sensor 2 battery_pct"
      scaled_voltage2:
        name: "Open Sensor 2 scaled_voltage2"
      battery_pct2:
        name: "Open Sensor 2 battery_pct2"
      extra:
        name: "Open Sensor 2 extra"
      on_event:
        then:
          - lambda: |-
              ESP_LOGD("example", "Open Sensor 2 '%s'/'%s'/%.0f/%.2fV/%.1f%%/%.2fV/%.1f%% triggered", event_type.c_str(), id(open_sensor_2)->get_history_tag().c_str(), id(open_sensor_2)->get_history_tag_type(), id(open_sensor_2)->get_scaled_voltage(), id(open_sensor_2)->get_battery_pct(), id(open_sensor_2)->get_scaled_voltage2(), id(open_sensor_2)->get_battery_pct2());
              if (id(open_sensor_2)->get_extra().length() > 0) {
                ESP_LOGD("example", "Open Sensor 2 extra: %s", libsesame3bt::core::util::bin2hex(id(open_sensor_2)->get_extra().data(), id(open_sensor_2)->get_extra().length()).c_str());
              } else {
                ESP_LOGD("example", "Open Sensor 2 extra: <empty>");
              }
